---
title: "Spatiotemporal predictors of juvenile salmonid marine survival in the Northern California Current"
author: "Markus Min"
date: "`r Sys.Date()`"
output:
  html_document
---

## Introduction

High inter-stock and inter-annual variation in adult returns of Columbia River Basin salmonids, many populations of which are listed under the Endangered Species Act (ESA), has led to an increased interest in understanding the mechanisms that govern marine survival in the Northern California Current (NCC). While many past studies have found some correlations between marine survival and indices that describe broad scale oceanographic or ecological phenomena (e.g., PDO or NPGO), these indices have become incresingly non-informative due to non-stationarity. In this project, we are seeking to re-examine the relationship between marine survival and ocean conditions by developing a statistical model that predicts marine survival based on the spatiotemporal overlap between juvenile salmonids and key members of the NCC food web. This requires integrating multiple data sources, primarily different fisheries-independent surveys that sample different trophic levels of the NCC food web.

<br>

## How to navigate this website

[Project Background](https://markusmin.github.io/JSOES-SDM/project_background.html) provides and overview of the literature on the marine survival of Columbia River Basin salmon, and places our proposed study within that context. [Project Description](https://markusmin.github.io/JSOES-SDM/project_description.html) then describes our hypotheses as informed by our conceptual understanding of the NCC food web, provides an overview of the modeling workflow, and explains how we propose to use different data sources in this project. 


Under the "Survey Descriptions" tab, you will find descriptions of the four primary fisheries-independent surveys that sample the pelagic NCC: the [Juvenile Salmon and Ocean Ecology Survey (JSOES)](https://markusmin.github.io/JSOES-SDM/jsoes_survey_description.html), the [California Current Ecosystem Survey (CCES)](https://markusmin.github.io/JSOES-SDM/CCES_survey_description.html), the [Pre-Recruit Survey (PRS)](https://markusmin.github.io/JSOES-SDM/PRS_survey_description.html), and the [Joint U.S.-Canada Integrated Ecosystem and Pacific Hake Acoustic Trawl Survey (Hake Survey)](https://markusmin.github.io/JSOES-SDM/hake_survey_description.html). In the description of each survey, particular emphasis is given to the trophic levels sampled by each survey, as well as their temporal and spatial extent, as these are key considerations for integrating data from different surveys.


The "Exploratory Analyses" tab contains data summaries and other exploratory analyses for each survey. So far, there are only preliminary analyses available for the [JSOES Bongo Data](https://markusmin.github.io/JSOES-SDM/bongo_exploratory.html) and the [JSOES Trawl Data](https://markusmin.github.io/JSOES-SDM/jsoes_trawl_exploratory.html).


This website is dynamic and will be updated as the project progresses. Please check back for updates!


