---
title: "JSOES Trawl Data Exploratory Analysis"
author: "Markus Min"
date: "`r Sys.Date()`"
output:
  html_document
---

This page contains exploratory analysis for the trawl data from JSOES.

```{r chunk-options, message = FALSE, echo = FALSE, warning = FALSE}
# set chunk options
knitr::opts_chunk$set(message = FALSE, echo = FALSE, warning = FALSE)
```


```{r load-libraries-reformat-data}
library(readxl)
library(here)
library(janitor)
library(tidyverse)
library(kableExtra)
library(sf)

#### Species data ####
jsoes <- clean_names(read_excel(here::here("Data", "Markus_Min_Trawl_CTD_Chl_Nuts_Thorson_Scheuerell_5.2.24_FINAL.xlsx")))

species_column_names <- colnames(jsoes)[32:ncol(jsoes)]

# change nmi to km to keep units consistent
jsoes %>% 
  mutate(km_from_shore = nmi_from_shore * 1.852) -> jsoes

jsoes %>% 
  pivot_longer(., cols = all_of(species_column_names), values_to = "n_per_km", names_to = "species") %>% 
  mutate(n = n_per_km*trawl_dist_km) -> jsoes_long
```

```{r load_spatial_data}
#### Spatial data ####
usa_spdf <- st_read("/Users/markusmin/Documents/ESA_RF_2021/map_files/USA_adm0.shp", quiet = TRUE)
# load BC
CAN_spdf <- st_read("/Users/markusmin/Documents/ESA_RF_2021/map_files/canada/lpr_000b16a_e.shp", quiet = TRUE)
BC_spdf <- filter(CAN_spdf, PRENAME == "British Columbia")
BC_proj <- st_transform(BC_spdf, crs = 4326)


# crop them to our desired area
US_west_coast <- sf::st_crop(usa_spdf,
    c(xmin = -126, ymin = 44, xmax = -123, ymax = 48.5))

BC_coast <- sf::st_crop(BC_proj,
    c(xmin = -126, ymin = 44, xmax = -123, ymax = 48.5))



# convert both shapefiles to a different projection (UTM zone 10) so that they can be plotted with the sdmTMB output
UTM_zone_10_crs <- 32610

US_west_coast_proj <- sf::st_transform(US_west_coast, crs = UTM_zone_10_crs)
BC_coast_proj <- sf::st_transform(BC_coast, crs = UTM_zone_10_crs)

# make this projection into kilometers
US_west_coast_proj_km <- st_as_sf(US_west_coast_proj$geometry/1000, crs = UTM_zone_10_crs)
BC_coast_proj_km <- st_as_sf(BC_coast_proj$geometry/1000, crs = UTM_zone_10_crs)
```

```{r create_basemap}
# create base map
survey_area_basemap_km <- ggplot(US_west_coast_proj_km) +
  geom_sf() +
  geom_sf(data = BC_coast_proj_km) +
  # coord_sf(ylim = c(4922.052, 5342.052), xlim = c(334.8638, 404.8638)) +
  # coord_sf(ylim = c(44,48.5),  xlim = c(-126, -123)) +
  ylab("Latitude")+
  xlab("Longitude")+
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill="white", color = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.14, 0.2),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        axis.ticks = element_blank(),
        axis.text = element_blank())
  # temporary fix for lat/long on axes to just get rid of them - start here to actually fix: https://forum.posit.co/t/converting-axes-to-lat-lon/27181

survey_area_basemap <- ggplot(US_west_coast) +
  geom_sf() +
  geom_sf(data = BC_coast) +
  coord_sf(ylim = c(44,48.5),  xlim = c(-126, -123)) +
  scale_x_continuous(breaks = c(124,125,126)) +
  ylab("Latitude")+
  xlab("Longitude")+
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill="white", color = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.14, 0.2),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))
```

```{r common_taxa}
## total density
jsoes_long %>% 
  group_by(species) %>% 
  summarise(mean_n_per_km = mean(n_per_km)) %>% 
  arrange(desc(mean_n_per_km)) -> jsoes_density_sums

jsoes_density_sums[1:10,] %>% 
  mutate(mean_n_per_km = round(mean_n_per_km, 1)) %>% 
  kbl(caption = "Top ten taxa by mean density.") %>% 
  kable_styling(latex_options = "HOLD_position")

## frequency of occurrence

# get count of each genus_species
jsoes_long %>% 
  filter(n > 0) %>% 
  count(species) %>% 
  arrange(desc(n)) %>% 
  mutate(prop_samples = n/nrow(jsoes)) -> jsoes_freq_occ

jsoes_freq_occ[1:10, ] %>% 
  mutate(prop_samples = round(prop_samples, 2)) %>% 
  kbl(caption = "Top ten taxa by frequency of occurrence.") %>% 
  kable_styling(latex_options = "HOLD_position")

```



#### Plotting distributions of some common taxa

Some focal taxa: 
- Coho salmon yearlings
- Interior Columbia Fall Chinook salmon yearlings
- Interior Columbia Spring Chinook salmon yearlings
- Water jellies (highest density taxon)

```{r prep_salmon_data}
csyis <- subset(jsoes_long, species == "chinook_salmon_yearling_interior_sp")
coho <- subset(jsoes_long, species == "coho_salmon_yearling")
csyif <- subset(jsoes_long, species == "chinook_salmon_yearling_interior_fa")
water_jellies <- subset(jsoes_long, species == "water_jelly")
```



```{r map_salmon}
plot_distribution <- function(data){
  # create facet_wrap plot for distribution across all years
  data %>% 
    mutate(encounter = ifelse(n_per_km == 0, "zero", "non-zero")) -> data
  
  survey_area_basemap +
      geom_point(data = data, aes(x = mid_long, y = mid_lat, size = n_per_km, color = encounter),
                 alpha = 0.5) +
    scale_color_manual(values = c("zero" = "#fc9272", "non-zero" = "#2ca25f")) +
    facet_wrap(~year, nrow = 3) +
    theme(legend.position = c(0.95, 0.1)) -> species_distribution_plot
  
  return(species_distribution_plot)
}

coho_dist_plot <- plot_distribution(data = coho)
csyis_dist_plot <- plot_distribution(data = csyis)
csyif_dist_plot <- plot_distribution(data = csyif)
water_jellies_dist_plot <- plot_distribution(data = water_jellies)

coho_dist_plot
csyis_dist_plot
csyif_dist_plot
water_jellies_dist_plot
```


```{r histograms}
hist(coho$n_per_km, breaks = 60)
hist(csyis$n_per_km, breaks = 60)
hist(csyif$n_per_km, breaks = 60)
hist(water_jellies$n_per_km, breaks = 60)

```



